[package]
name = "latke"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = "0.6.4"
saber = { path = "../saber-rust" }
pqcrypto-dilithium = { path = "../pqcrypto/pqcrypto-dilithium" }
hkdf = "0.12"
sha2 = "0.10"
lioness = "0.1.2"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "all"
harness = false
