[package]
name = "latke"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = "0.6.4"
saber = { path = "../saber-rust" }
pqcrypto-dilithium = { path = "../pqcrypto/pqcrypto-dilithium" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "all"
harness = false
